pipeline {
    agent any

    environment {
        IMAGE = "yourdockerhubusername/devops-app:latest"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/YOUR_USERNAME/YOUR_REPO.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE ./app'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $IMAGE'
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: $IMAGE|g" k8s/deployment.yaml
                '''
            }
        }

        stage('Commit Changes') {
            steps {
                sh '''
                git config --global user.email "you@example.com"
                git config --global user.name "jenkins"

                git add .
                git commit -m "Updated image tag"
                git push origin main
                '''
            }
        }
    }
}
