pipeline {
    agent any

    environment {
        IMAGE_NAME = "devops-app"
        DOCKERHUB_USER = "rupalkatre"
        DOCKER_CRED = "docker-creds"
        GIT_CRED = "github-creds"
        REPO_URL = "https://github.com/rupalkatre133/devops-project.git"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER} -f app/src/Dockerfile app/src
                '''
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "${DOCKER_CRED}",
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                '''
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}|g" k8s/deployment.yaml
                '''
            }
        }

        stage('Commit & Push Changes') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "${GIT_CRED}",
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    sh '''
                    git config --global user.email "you@example.com"
                    git config --global user.name "jenkins"

                    git add k8s/deployment.yaml
                    git commit -m "Updated image to build ${BUILD_NUMBER}" || echo "No changes to commit"

                    git push https://${GIT_USER}:${GIT_PASS}@github.com/rupalkatre133/devops-project.git HEAD:main
                    '''
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withCredentials([file(credentialsId: 'eks-kubeconfig', variable: 'KUBECONFIG')]) {
                    sh '''
                    kubectl get nodes
                    kubectl apply -f k8s/deployment.yaml
                    kubectl apply -f k8s/service.yaml
                    '''
                }
            }
        }
    }
}
